name: retro
description: App for configuring and populating a post-sprint retro board
version: 0.0.1
authors:
  - Jerold Albertson <jerold.albertson@workiva.com>
#homepage: https://www.github.io/jerold/retro

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular2: 2.2.0
  bootstrap: ^3.3.7
  browser: ">=0.10.0 <0.11.0"
  dart_to_js_script_rewriter: ^1.0.1
  firebase: 3.0.0
  meta: 1.0.4

dev_dependencies:
  build: ^0.4.0
  built_value_generator: ^0.4.3
  test: any

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter